In [3]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [4]:
# 합계,평균,결과 컬럼을 추가
# 결과 평균점수가 70점이상은 합격, 불합격으로 출력하시오.
df['합계'] = df['국어'] + df['영어'] + df['수학']
df['평균'] = df['합계'] / 3
df['결과'] = '불합격'
df.loc[df['평균'] >= 70, '결과'] = '합격'

In [5]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기', '합계', '평균',
       '결과'],
      dtype='str')

In [1]:
# 컬럼순서변경
# df2 = df[['이름','평균','결과']]
# df2
# df = df[['이름','평균','결과','학교','학년', '키', '국어', '영어', '수학', 'SW특기', '합계']]

In [7]:
df.value_counts('결과') # 그룹으로 개수확인

결과
합격     4
불합격    4
Name: count, dtype: int64

In [8]:
df

       이름         평균   결과    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래  91.666667   합격   구로고  197   90   85  100  95  85      Python  275
2번    강태원  41.666667  불합격   구로고  184   40   35   50  55  25        Java  125
3번    강호림  75.000000   합격   구로고  168   80   75   70  80  75  Javascript  225
4번    김수찬  56.666667  불합격   구로고  187   40   60   70  75  80         NaN  170
5번    김재욱  15.000000  불합격   구로고  188   15   20   10  35  10         NaN   45
6번    박동현  91.666667   합격  디지털고  202   80  100   95  85  80           C  275
7번    박혜정  55.000000  불합격  디지털고  188   55   65   45  40  35      PYTHON  165
8번    승근열  91.666667   합격  디지털고  190  100   85   90  95  95          C#  275

In [9]:
cols = list(df.columns)

In [10]:
cols

['이름', '평균', '결과', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기', '합계']

In [11]:
a_list = [1,2,3]
b_list = [4,5,6]
c = a_list + b_list
c

[1, 2, 3, 4, 5, 6]

In [12]:
# {cols리스트 순서를 변경}

# 1. 리스트 타입으로 변경후 순서를 변경
# cols = list(df.columns) 

# cols[-2:] # 평균, 결과 컬럼
# cols[:-2] # 이름 ~ 합계
# cols[0]
# type(cols[0]) # 타입 str -> list타입으로 변경하려면 []로 묶어야함
# type(cols[1:-2]) # 학교 ~ 합계 ,list
# 2. 리스트 순서 변경
cols = [cols[0]]+cols[-2:]+cols[1:-2] # str + list + list => error

# 3. 변경된 리스트 적용
df = df[cols]

In [13]:
# 컬럼수정 - replace, 존재하는 컬럼에 값을 입력하면 수정됨
# 컬럼추가 - 없는 컬럼에 값을 입력하면 추가됨
# 컬럼삭제 - drop : 여러개 삭제 가능, inplace = True 적용

In [14]:
df.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [15]:
filt = df['수학'] > 80
filt.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [16]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# row : index수정, 추가, 삭제
# index 삭제 - 조건사용해서 삭제
# df.loc[df['평균'] >= 70, '결과'] = '합격'
# 수학점수가 80점미만 학생 삭제
filt = df['수학'] < 80
# df2 = df[filt]
# df2

# 컬럼삭제
# df.drop(columns=['평균','결과'],inplace=True) # 컬럼삭제]

# [ index row 삭제]
# df.drop(index=['1번','2번'],inplace=True) # index 삭제
# 2. 조건을 이용한 index 삭제
# df.drop(index=df[filt].index,inplace=True) # index 삭제

In [ ]:
# 1.index 추가 : loc[] 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동','구로고',190,90,80,70,60,50,'Python']

# 2.SW특기 부분 값 추가
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력

# 3.부분 학교,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']] = ['디지털고','Python']
# df.loc['5번',['학교','사회','SW특기']] = ['디지털고',50,'Java']

In [ ]:
# 컬럼 이름 변경
# df2.columns = [변경할 이름']
# df2 = df[['이름','국어','영어']]
# df2.columns = ['name','kor','eng'] # 컬럼명 변경
# df2

# 부분 컬럼이름 변경 : rename
# df.rename(columns={'이름':'name','국어':'kor','영어':'eng'},inplace=True)
# df

# df.columns[1] = 'school' # 안됨
df.rename(columns={df.columns[1]:'school'},inplace=True)

     name    학교    키  kor  eng   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# df.loc['4번','이름'] = '홍길순'
# df['영어'] = 0

In [ ]:
df.columns
# 1.국어, 영어, 수학, 과학, 사회 합계 컬럼을 추가
# 2.합계점수가 350점 이상만 출력하시오.
df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
file = df['합계'] >=350
df[file] # 350점 이상만 출력
# df2 = df[file] # 350점 이상만 출력
# df2
# 3. 350점 미만 삭제후 출력
df.drop(index=df[~file].index,inplace=True) # index삭제
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465