In [12]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # -부호 처리
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # 한글처리 : 윈도우 맑은고딕 저장
matplotlib.rcParams['font.size'] = 15   # 전체 글자폰튼크기 조정
# matplotlib.rcParams['font.family'] = 'AppleGothic'    # 맥컴 애플고딕 저장
import pandas as pd
import numpy as np

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

In [14]:
df = pd.read_csv('file/namu1.csv')
df.head(3)

   Unnamed: 0     title                                                url
0           0   시라유키 히나  https://namu.wiki/w/%EC%8B%9C%EB%9D%BC%EC%9C%A...
1           1   스미요시 리온  https://namu.wiki/w/%EC%8A%A4%EB%AF%B8%EC%9A%9...
2           2  위 아 애니멀스  https://namu.wiki/w/%EC%9C%84%20%EC%95%84%20%E...

In [8]:
df['url']

0     https://namu.wiki/w/%EC%8B%9C%EB%9D%BC%EC%9C%A...
1     https://namu.wiki/w/%EC%8A%A4%EB%AF%B8%EC%9A%9...
2     https://namu.wiki/w/%EC%9C%84%20%EC%95%84%20%E...
3       https://namu.wiki/w/%EB%B0%B1%EC%98%88%EC%8A%AC
4     https://namu.wiki/w/2023%20%EC%87%BC%ED%8A%B8%...
                            ...
95    https://namu.wiki/w/2008%EB%85%84/%EC%82%AC%EB...
96    https://namu.wiki/w/616%EB%B2%88%20%EA%B5%90%E...
97      https://namu.wiki/w/%EC%97%90%EC%9D%B4%EB%82%98
98    https://namu.wiki/w/%EC%95%88%EC%96%91%20%EC%A...
99    https://namu.wiki/w/%EB%A7%88%EC%A7%80%EB%AC%B...
Name: url, Length: 100, dtype: str

In [15]:
for url in df['url'].head(50):
    print(url)

https://namu.wiki/w/%EC%8B%9C%EB%9D%BC%EC%9C%A0%ED%82%A4%20%ED%9E%88%EB%82%98
https://namu.wiki/w/%EC%8A%A4%EB%AF%B8%EC%9A%94%EC%8B%9C%20%EB%A6%AC%EC%98%A8
https://namu.wiki/w/%EC%9C%84%20%EC%95%84%20%EC%95%A0%EB%8B%88%EB%A9%80%EC%8A%A4
https://namu.wiki/w/%EB%B0%B1%EC%98%88%EC%8A%AC
https://namu.wiki/w/2023%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90/%EB%8C%80%ED%95%99%EC%9B%90/%EC%B9%98%EC%9D%98%ED%95%99%EB%8C%80%ED%95%99%EC%9B%90
https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EC%9E%84%EB%AC%B4/%EB%A7%88%EC%8B%A0%20%EC%9E%84%EB%AC%B4/%EC%A0%9C7%EC%9E%A5
https://namu.wiki/w/%EA%B2%BD%EC%A2%85(%EC%A1%B0%EC%84%A0)/%EB%8F%85%EC%82%B4%EC%84%A4
https://namu.wiki/w/%EB%AA%AC%EC%8A%A4%ED%84%B0%EB%B2%84%EC%8A%A4
https://namu.wiki/w/GIVE%20ME%20FIVE%2C%20KEEP%20THAT%20VIBE
https://namu.wiki/w/%EB%B0%95%EC%8A%B9%EC%88%98
https://namu.wiki/w/2022%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%EC%A0%A4%EB%8B%A4%EC%9D%98%20%EC%A0%84%EC%84%A4%20%EC%8B%9C%EA%B0%84%EC%9D%98%20%EC%98%A4%EC%B9%B4%EB%A6%AC%EB%82%98(2026)
https://namu.wiki/w/%ED%83%88%ED%83%9C
https://namu.wiki/w/%EC%A7%80%EC%9A%B0%EA%B0%9C
https://namu.wiki/w/%EB%B0%B1%EC%98%88%EC%8A%AC
https://namu.wiki/w/%ED%95%A9%EB%8F%99%EA%B5%B0
https://namu.wiki/w/%ED%8B%80:%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98%20%EC%B9%98%EA%B3%BC%EB%8C%80%ED%95%99
https://namu.wiki/w/%EB%A7%A4%EB%8B%88%ED%81%90%EC%96%B4/%EC%BA%90%EB%A6%AD%ED%84%B0
https://namu.wiki/w/%ED%85%8C%EB%9D%BC%20%EB%A0%88%EC%9D%B4%EB%93%9C%EB%B0%B0%ED%8B%80
https://namu.wiki/w/%EC%9C%84%EC%9D%B8%20%EA%B4%80%EB%A0%A8%20%EC%A0%95%EB%B3%B4
https://namu.wiki/w/2021%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%ED%81%90%EB%B2%A0%EB%A0%88%EC%9D%B4
https://namu.wiki/w/%EB%8C%80%EA%B5%AC%EA%B0%84%EC%86%A1%EB%AF%B8%EC%88%A0%EA%B4%80
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90%20%EC%B9%98%EC%9D%98%ED%95%99%EB%8C%80%ED%95%99%EC%9B%90%20%EB%A1%9C%EA%B3%A0.png
https://namu.wiki/w/%EC%98%A4%EB%A7%88%EC%9D%B4%EA%B1%B8/%EA%B3%B5%EC%97%B0%20%EB%B0%8F%20%ED%96%89%EC%82%AC
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:SamSara
https://namu.wiki/w/%ED%8F%B4%20%EA%B0%9C%EC%8A%A4%EC%BD%94%EC%9D%B8
https://namu.wiki/w/%EC%98%81%ED%98%BC%EC%9D%98%20%EC%84%B1%EB%AC%BC%ED%95%A8(%ED%95%98%EC%8A%A4%EC%8A%A4%ED%86%A4)
https://namu.wiki/w/%EC%9C%84%EC%9D%B8%20%EA%B4%80%EB%A0%A8%20%EC%A0%95%EB%B3%B4
https://namu.wiki/w/%EB%AA%AC%EC%8A%A4%ED%84%B0(%EB%A8%BC%EC%9E%91%EA%B7%80)
https://namu.wiki/w/%EA%B9%80%EB%AF%BC%EC%9E%AC
https://namu.wiki/w/2020%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/Google%2B
https://namu.wiki/w/%EC%98%A4%EC%B9%B4%EB%AA%A8%ED%86%A0%20%EB%AF%B8%EC%93%B0%EB%82%98%EB%A6%AC
https://namu.wiki/w/%ED%8F%AC%ED%95%B8%EC%A6%88
https://namu.wiki/w/SELECTION%20BOX%20Vol.5
https://namu.wiki/w/%EB%8D%B1%EC%8A%A4(%EB%B0%A9%EC%86%A1%EC%9D%B8)/%ED%94%BC%EC%9D%98%20%EA%B2%8C%EC%9E%84
https://namu.wiki/w/%EC%9B%94%EB%B4%89%EC%97%AD
https://namu.wiki/w/I%20SPY(NCT%20WISH)
https://namu.wiki/w/%EC%9D%B4%EA%B0%95%EB%AA%A8
https://namu.wiki/w/2019%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%EC%95%88%EC%96%91%20%EC%A0%95%EA%B4%80%EC%9E%A5%20%EB%A0%88%EB%93%9C%EB%B6%80%EC%8A%A4%ED%84%B0%EC%8A%A4
https://namu.wiki/w/%EC%A0%95%EB%B3%B5%EC%9E%90%20%EC%BA%89(90%EB%85%84%EB%8C%80%20%EB%A7%88%EB%B8%94%20%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98%20%EC%8B%9C%EB%A6%AC%EC%A6%88)
https://namu.wiki/w/%EC%86%8C%EB%85%80%20(%EB%A6%AC%EB%93%AC%20%EC%B2%9C%EA%B5%AD%20%EC%8B%9C%EB%A6%AC%EC%A6%88)
https://namu.wiki/w/%EA%B9%80%EB%8F%99%EC%97%BD(1990)
https://namu.wiki/w/2018%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%A3%BC%EB%8B%88%EC%96%B4%20%EC%84%B8%EA%B3%84%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%ED%94%BC%EB%8B%89%EC%8A%A4(%ED%81%B4%EB%9E%98%EC%8B%9C%20%EC%98%A4%EB%B8%8C%20%ED%81%B4%EB%9E%9C)
https://namu.wiki/w/%ED%82%B9%20%EC%A0%9C%EC%9E%84%EC%8A%A4%20%EC%84%B1%EA%B2%BD
https://namu.wiki/w/%EB%AA%AC%EC%8A%A4%ED%84%B0(%EB%A8%BC%EC%9E%91%EA%B7%80)

In [16]:
url = 'https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84'
res = requests.get(url)
soup = BeautifulSoup(res.text,'lxml')
title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True)
category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True)
content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

In [18]:
data = []
for url in df['url'].head(50):
    # # 2. selenium : 자동화 도구 - 스크롤없이 가져옴
    # namu_url = url
    # options = Options()
    # options.add_experimental_option("excludeSwitches", ["enable-automation"])
    # options.add_experimental_option("useAutomationExtension", False)
    # options.add_argument("--disable-blink-features=AutomationControlled")
    # browser = webdriver.Chrome(options=options)
    # browser.maximize_window() # 화면 최대창 확대
    # browser.get(namu_url)
    # time.sleep(2)
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml')
    title_tag = soup.find('a',{'class':'J23-5aq4'})
    title = title_tag.get_text(strip=True) if title_tag else None
    category_tag = soup.find('ul',{'class':'EVpyuXop'})
    category = category_tag.get_text(strip=True) if category_tag else None
    content_tag = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content_tag.get_text(strip=True) if content_tag else None
    data.append({
        'title':title,
        'category':category,
        'content':content
    })
    print(title)

print('완료')
# # # 파일저장
# soup = BeautifulSoup(browser.page_source,'lxml')
# with open('file/namu_con1.html','w',encoding='utf-8') as f:
#     f.write(soup.prettify())

시라유키 히나
스미요시 리온
위 아 애니멀스
백예슬
2023 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
서울대학교/대학원/치의학대학원
원신/임무/마신 임무/제7장
경종(조선)/독살설
몬스터버스
GIVE ME FIVE, KEEP THAT VIBE
박승수
2022 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
젤다의 전설 시간의 오카리나(2026)
탈태
지우개
백예슬
합동군
틀:대한민국의 치과대학
매니큐어/캐릭터
테라 레이드배틀
위인 관련 정보
2021 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
큐베레이
대구간송미술관
None
오마이걸/공연 및 행사
사용자:SamSara
폴 개스코인
영혼의 성물함(하스스톤)
위인 관련 정보
몬스터(먼작귀)
김민재
2020 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
Google+
오카모토 미쓰나리
포핸즈
SELECTION BOX Vol.5
덱스(방송인)/피의 게임
월봉역
I SPY(NCT WISH)
이강모
2019 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
안양 정관장 레드부스터스
정복자 캉(90년대 마블 애니메이션 시리즈)
소녀 (리듬 천국 시리즈)
김동엽(1990)
2018 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회
피닉스(클래시 오브 클랜)
킹 제임스 성경
몬스터(먼작귀)
완료

In [ ]:
n_df = pd.DataFrame(data)
n_df.to_csv('file/namu2.csv')
n_df

,title,category,content
0,시라유키 히나,시라유키 히나스텔라이브/소속 크리에이터치지직 파트너 스트리머대한민국의 여성 인터넷 ...,편집 보호된 문서입니다. 문서의ACL 탭을 확인하세요.스텔라이브StelLive소속 ...
1,스미요시 리온,일본의 여자 싱글 스케이팅 선수도쿄도 출신 인물2003년 출생2018년 데뷔메이지대...,역대동계 세계대학경기대회 여자 싱글챔피언[ 펼치기 · 접기 ]1회1960 샤모니지트...
2,위 아 애니멀스,웹툰/목록2016년 웹툰카카오웹툰/서비스 종료네이버 웹툰/추천완결,위 아 애니멀스글/그림우블루연재 사이트다음 웹툰연재 날짜2016년 12월 22일 ~...
3,백예슬,한국 여가수발라드 가수1996년 출생미스트롯4 출연자수원 백씨,백예슬Baek Ye Seul출생1996년4월 16일(30세)국적대한민국학력동덕여자대...
4,2023 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,←2021-22ISU 쇼트트랙 스피드 스케이팅 2022-23 시즌2023-24→[ ...
5,서울대학교/대학원/치의학대학원,서울대학교/학부서울대학교 대학원치과대학,상위 문서:서울대학교/대학원서울대학교의 단과대학인문대학사회과학대학자연과학대학간호대학...
6,원신/임무/마신 임무/제7장,원신/임무게임 스토리,상위 문서:원신/임무/마신 임무관련 문서:원신/스토리이 문서에스포일러가 포함되어 있...
7,경종(조선)/독살설,경종(조선)영조음모론게장건과조선(18세기)인터넷 밈/역사,상위 문서:경종(조선)음모론Conspiracy Theory[ 펼치기 · 접기 ]분류...
8,몬스터버스,몬스터버스고지라 시리즈킹콩 시리즈공포 영화 시리즈워너 브라더스 픽처스레전더리 엔터테...,몬스터버스 관련 틀[ 펼치기 · 접기 ][ 펼치기 · 접기 ]고질라 시리즈고질라고질...
9,"GIVE ME FIVE, KEEP THAT VIBE",VERIVERY2026년 콘서트,VERIVERY베리베리동헌호영민찬계현연호용승강민한국 음반일본 음반기타 음반관련 문서...
10,박승수,박승수대한민국의 남자 축구 선수2007년 출생능동중학교(경기) 출신매탄고등학교 출신...,동명이인에 대한 내용은박승수(동명이인)문서를 참고하십시오.한시적 넘겨주기로 연결되는...
11,2022 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 세계선수권 대회,←2020-21ISU 쇼트트랙 스피드 스케이팅 2021-22 시즌2022-23→[ ...
12,젤다의 전설 시간의 오카리나(2026),출시 예정 게임공개 전 정보(게임)젤다의 전설 시간의 오카리나2026년 Ninten...,젤다의 전설메인 시리즈 일람[ 펼치기 · 접기 ]2D젤다의 전설링크의 모험신들의 트...
13,탈태,하스스톤/카드/주문/지옥,◀갈라크론드의 부활스칼로맨스 아카데미▶황폐한 아웃랜드직업 전설[ 펼치기 · 접기 ]...
14,지우개,지우개순우리말영국의 발명품필기구18세기 도입된 제품학용품,다른 동음이의어에 대한 내용은지우개(동음이의어)문서를 참고하십시오.🛒 생활용품 🧺[...
15,백예슬,한국 여가수발라드 가수1996년 출생미스트롯4 출연자수원 백씨,백예슬Baek Ye Seul출생1996년4월 16일(30세)국적대한민국학력동덕여자대...
16,합동군,군사 편제군종,군종(軍種)[ 펼치기 · 접기 ]법적 지위정규군준군사조직(법집행기관)비정규군소속 관...
17,틀:대한민국의 치과대학,치과대학치의학전문대학원둘러보기 틀/단과대학둘러보기 틀/대학원,대한민국의치과대학및치의학전문대학원[ 펼치기 · 접기 ]서울국립서울대학교 치의학대학원...
18,매니큐어/캐릭터,화장품캐릭터 목록,상위 문서:매니큐어이 문서에스포일러가 포함되어 있습니다.이 문서가 설명하는 작품이나...
19,테라 레이드배틀,포켓몬스터/배틀 시설테라스탈,포켓몬스터 역대 배틀 시설[ 펼치기 · 접기 ]2세대배틀타워3세대배틀타워트레이너타워...
20,위인 관련 정보,인물화폐의 인물,태어난 연도순으로 정리해주세요.1. 개요2. 목록2.1. 세계인물2.1.1. 지도자...
21,2021 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회취소된 스포츠 행사코로나바이러스감염증...,본 계획은 취소 또는 무산되었습니다.본 문서 또는 문단에서 다루는 계획은 본래 시행...
22,큐베레이,큐베레이,U.C. 0087.-0088.그리프스 전역등장 모빌슈트[ 에우고 · 카라바 ]A.E...
23,대구간송미술관,간송미술관대구광역시의 미술관수성구의 문화 시설수성구의 교육 시설인명 유래 시설명20...,대구광역시관내 박물관[ 펼치기 · 접기 ]국립국립대구박물관국립대구과학관국립대구기상과...
24,NaN,NaN,NaN
25,오마이걸/공연 및 행사,오마이걸/활동아이돌/공연,상위 문서:오마이걸오마이걸OH MY GIRL효정미미유아승희유빈아린[ 전 멤버 ]진이...
26,사용자:SamSara,NaN,NaN
27,폴 개스코인,1967년 출생1985년 데뷔2004년 은퇴게이츠헤드 출신 인물아일랜드계 영국인잉글...,폴 개스코인의 수상 이력[ 펼치기 · 접기 ]둘러보기 틀 모음개인 수상1987-88...
28,영혼의 성물함(하스스톤),하스스톤/카드/하수인하스스톤/키워드/생명력 흡수하스스톤/키워드/죽음의 메아리,◀갈라크론드의 부활스칼로맨스 아카데미▶황폐한 아웃랜드직업 전설[ 펼치기 · 접기 ]...
29,위인 관련 정보,인물화폐의 인물,태어난 연도순으로 정리해주세요.1. 개요2. 목록2.1. 세계인물2.1.1. 지도자...
30,몬스터(먼작귀),먼작귀/등장인물,등장인물(몬스터)·설정·만화·애니메이션(TVA·극장판)1. 개요2. 상세2.1. 키...
31,김민재,김민재1996년 출생통영시 출신 인물안동 김씨(선)가야초등학교(경남) 출신연초중학교...,FC 바이에른 뮌헨에서의 경기 및 활약상에 대한 내용은김민재/클럽 경력/2026-2...
32,2020 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,←2018-19ISU 쇼트트랙 스피드 스케이팅 2019-20 시즌2020-21→[ ...
33,Google+,구글 애플리케이션소셜 네트워크 서비스2019년 폐지,구글애플리케이션[ 펼치기 · 접기 ]개인화 및 소셜구글 제미나이구글 어시스턴트휴대전...
34,오카모토 미쓰나리,일본의 남성 정치인공명당 국회의원중도개혁연합 국회의원제46대 일본 중의원 의원제47...,공명당대표[ 펼치기 · 접기 ]초대칸자키 타케노리제2대오타 아키히로제3대야마구치 나...
35,포핸즈,포핸즈tvN 토일 드라마2026년 드라마청춘 드라마휴먼 드라마성장 드라마학원 드라마...,Four Hands은(는) 여기로 연결됩니다. 한 대의 피아노를 두 사람이 동시에 ...
36,SELECTION BOX Vol.5,유희왕 듀얼링크스/셀렉션 박스,듀얼링크스의 상점[ Speed 듀얼 ][ BOX 일람 ]메인 BOX미니 BOXWIN...
37,덱스(방송인)/피의 게임,피의 게임/인물별 활동 내역,상위 문서:덱스(방송인)▢ 시즌 1✓ 시즌 1▢ 시즌 2✓ 시즌 2▢ 시즌 3✓ 시...
38,월봉역,은률선1929년 개업한 철도역삼천군의 철도역,폐역월봉-야촌-수교月峯驛 / Wŏlbong Station월봉역다른 문자 표기로마자W...
39,I SPY(NCT WISH),NCT WISH/음반2026년 EP한국의 음반출시 예정 음반Dolby Atmos 지...,이 문서는 공식적으로 공개되지 않은 NCT WISH의 미니 4집에 대해 다룹니다.루...
40,이강모,자이언트(드라마)/등장인물한국 드라마 캐릭터,창사 20주년 대하 드라마[ 펼치기 · 접기 ]설정·탐구·평가등장인물주요 인물이강모...
41,2019 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,←2017-18ISU 쇼트트랙 스피드 스케이팅 2018-19 시즌2019-20→[ ...
42,안양 정관장 레드부스터스,안양 정관장 레드부스터스한국인삼공사안양시 연고 구단대한민국의 프로 농구단한국프로농구...,2026-27 시즌에 대한 내용은안양 정관장 레드부스터스/2026-27 시즌문서를 ...
43,정복자 캉(90년대 마블 애니메이션 시리즈),엑스맨 '97/등장인물정복자 캉,상위 문서:엑스맨(1992년 애니메이션)/등장인물마블 시네마틱 유니버스정복자 캉[ ...
44,소녀 (리듬 천국 시리즈),리듬 천국 시리즈/캐릭터리듬 천국/수록 게임리듬 세상/수록 게임리듬 세상 Wii/수...,프로필이름소녀ユカGirl등장 시리즈리듬 천국리듬 세상리듬 세상 Wii리듬 세상 더 ...
45,김동엽(1990),김동엽(1990)대한민국의 남자 야구 선수1990년 출생2016년 데뷔야구 선수 자...,울산 웨일즈2027 시즌외야수[ 펼치기 · 접기 ]3김서원·8최준서·20김동엽·23...
46,2018 쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,쇼트트랙 스피드 스케이팅 주니어 세계선수권 대회,←2016-17ISU 쇼트트랙 스피드 스케이팅 2017-18 시즌2018-19→[ ...
47,피닉스(클래시 오브 클랜),클래시 오브 클랜/펫,클래시 로얄의 피닉스에 대한 내용은피닉스(클래시 로얄)문서를 참고하십시오.클래시 오...
48,킹 제임스 성경,킹 제임스 성경영어 성경영국의 도서17세기 도서케임브리지 대학교 출판부옥스퍼드 대학교,성경의 필사본과 번역[ 펼치기 · 접기 ]고대 언어사해문서(히브리어)·70인역(코이...
49,몬스터(먼작귀),먼작귀/등장인물,등장인물(몬스터)·설정·만화·애니메이션(TVA·극장판)1. 개요2. 상세2.1. 키...